kind: ConfigMap
apiVersion: v1
metadata:
  name: ssl-config
data:
  ssl.cnf: |-
    [mysqld]
    ssl_key=/certs/tls.key
    ssl_cert=/certs/tls.crt
    ssl_ca=/certs/ca.crt
    require_secure_transport=OFF
