apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: native-ha-qm
spec:
  queueManager:
    storage:
      defaultClass: ibmc-block-gold
      queueManager:
        class: ibmc-block-gold
      persistedData:
        class: ibmc-block-gold
      recoveryLogs:
        class: ibmc-block-gold
