apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  name: instance
  namespace: openshift-logging
spec:
  logStore:
    elasticsearch:
      storage:
        storageClassName: ocs-storagecluster-ceph-rbd
   
