apiVersion: appconnect.ibm.com/v1beta1
kind: DesignerAuthoring
metadata:
  name: designer-authoring
spec:
  couchdb:
    logLevel: info
    replicas: 1
    storage:
      size: 10Gi
      type: ephemeral
  designerFlowsOperationMode: local
  designerMappingAssist:
    enabled: true
    incrementalLearning:
      schedule: Every 15 days
  license:
    accept: true
    license: L-XRNH-47FJAW
    use: CloudPakForIntegrationNonProduction
  replicas: 1
  version: '12.0'
