apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationRuntime
metadata:
  name: sample-integrationruntime
  annotations:
    # https://www.ibm.com/docs/en/app-connect/container?topic=troubleshooting-integration-servers-in-app-connect-dashboard#validatingwebhook__title__1
    appconnect.ibm.com/webhook-barcheck: NONE
spec:
  license:
    accept: true
    license: L-KPRV-AUG9NC
    use: CloudPakForIntegrationNonProduction
  restApiHTTPS:
    enabled: true
  flowType:
    toolkitFlow: true
  forceFlowsHTTPS:
    enabled: true
    secretName: default-cert-copy
  dashboardUsers:
    bypassGenerate: false
  version: '13.0.1.0-r2'
  template:
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: sample-configmap
      containers:
        - name: runtime
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
          #env:
            #- name: MY_CUSTOM_ENV_VAR
            #  value: 'true'
            #- name: ANOTHER_ENV_VAR
            #  value: '100'
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi
  logFormat: basic
  replicas: 1
  barURL:
    - https://github.com/Nordic-MVP-GitOps-Repos/ace-hello-world/raw/main/ace-hello-world.bar
  configurations:
    - empty-credentials
    - serverconf-configuration
  defaultNetworkPolicy:
    enabled: true
