apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: sample-is
  namespace: cp4i
spec:
  adminServerSecure: true
  createDashboardUsers: true
  designerFlowsOperationMode: disabled
  enableMetrics: true
  license:
    accept: true
    license: L-MJTK-WUU8HE
    use: CloudPakForIntegrationNonProduction
  pod:
    containers:
      runtime:
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 512Mi
  replicas: 1
  router:
    timeout: 120s
  service:
    endpointType: https
  forceFlowHTTPS:
    enabled: true
    secretName: default-cert-copy
  version: "12.0"
  barURL: >-
    https://github.com/Nordic-MVP-GitOps-Repos/ace-hello-world/raw/main/ace-hello-world.bar,https://github.com/Nordic-MVP-GitOps-Repos/ace-mq-request-respone/blob/main/HttpMQApp.bar
  configurations:
    - empty-credentials
    - ace-mq-policy
    - remote-mq
