apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaConnect
metadata:
  name: kafka-connect
  annotations:
    eventstreams.ibm.com/use-connector-resources: "true"
spec:
  bootstrapServers: minimal-prod-kafka-bootstrap.cp4i.svc:9093
  config:
    group.id: connect-cluster
    config.storage.replication.factor: 1
    config.storage.topic: connect-cluster-configs  
    offset.storage.replication.factor: 1
    offset.storage.topic: connect-cluster-offsets
    status.storage.replication.factor: 1
    status.storage.topic: connect-cluster-status
  replicas: 1
  authentication:
    certificateAndKey:
      certificate: user.crt
      key: user.key
      secretName: kafka-connect-user
    type: tls
  tls:
    trustedCertificates:
      - certificate: ca.crt
        secretName: minimal-prod-cluster-ca-cert
  resources:
    limits:
      cpu: 2000m
      memory: 2Gi
    requests:
      cpu: 1000m
      memory: 2Gi
  template:
    connectContainer:
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        privileged: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
    buildConfig:
        pullSecret: ibm-entitlement-key
    pod:
      metadata:
        annotations:
          cloudpakId: c8b82d189e7545f0892db9ef2731b90d
          productVersion: 11.4.0
          productID: 2a79e49111f44ec3acd89608e56138f5
          cloudpakName: IBM Cloud Pak for Integration
          productChargedContainers: kafka-connect-connect
          productCloudpakRatio: '2:1'
          productName: IBM Event Streams for Non Production
          eventstreams.production.type: CloudPakForIntegrationNonProduction
          productMetric: VIRTUAL_PROCESSOR_CORE
      imagePullSecrets: []
  build:
    output:
      type: docker
      image: image-registry.openshift-image-registry.svc:5000/cp4i/mq-source-and-datagen-connectors:0.0.1
    plugins:
      - name: datagen
        artifacts:
          - type: jar
            url: https://github.com/IBM/kafka-connect-loosehangerjeans-source/releases/download/0.0.1/kafka-connect-loosehangerjeans-source-0.0.1-jar-with-dependencies.jar
      - name: mq-source
        artifacts:
          - type: jar
            url: https://github.com/ibm-messaging/kafka-connect-mq-source/releases/download/v1.3.3/kafka-connect-mq-source-1.3.3-jar-with-dependencies.jar
