apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cp4i-operators
spec:
  generators:
  - list:
      elements:
        - name: openshift-cert-manager
          namespace: cert-manager-operator
        - name: platformnavigator
          namespace: cp4i
        #- name: apiconnect
        #  namespace: openshift-operators
        #- name: appconnect
        #  namespace: openshift-operators
        #- name: mq
        #  namespace: openshift-operators
        #- name: eventstreams
        #  namespace: openshift-operators
        #- name: eventendpointmgmt
        #  namespace: openshift-operators
        #- name: eventprocessing
        #  namespace: openshift-operators
        #- name: flink
        #  namespace: openshift-operators
        #- name: openshift-logging
        #  namespace: openshift-logging
        #- name: openshift-pipelines
        #  namespace: openshift-operators
        #- name: cert-utils
        #  namespace: cert-utils-operator       
        #- name: instana-agent
        #  namespace: openshift-operators
        #- name: clusterresourceoverride
        #  namespace: cp4i
        #- name: assetrepository
        #  namespace: openshift-operators
  template:
    metadata:
      name: '{{name}}-operator'
      labels:
        group: applications
      annotations:
        argocd.argoproj.io/sync-wave: "100"
    spec:
      project: cp4i-operators
      source:
        path: 'components/{{name}}/operator'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          selfHeal: true
