kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ibm-flink-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: ocs-storagecluster-cephfs
