apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: native-ha-qm
  annotations:
    certmanager.k8s.io/disable-auto-restart: "true"
    configmap.reloader.stakater.com/reload: "native-ha-qm-configmap"
    secret.reloader.stakater.com/reload: "mq-nativeha-internal-tls-secret,mq-external-tls-secret"
spec:
  #telemetry:
  #  tracing:
  #    instana:
  #      enabled: true
  license:
    accept: true
    license: PATCHED_BY_KUSTOMIZE
    metric: VirtualProcessorCore
    use: PATCHED_BY_KUSTOMIZE
  securityContext:
    supplementalGroups: [99]
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: "yes"
            # For instana tracing,
            #- name: IBMMQ_RFH2_HEADERS_TO_EXPOSE
            #  value: 'usr.<custome element1>, usr.<custom element 2>'
            # For otel tracing
            #- name: LOG_LEVEL
            #  value: debug
            #- name: MONITOR_LEVEL
            #  value: debug
            #- name: SPAN_FORMAT
            #  value: otel
            #- name: OTLP_EXPORTER_GRPC_ENDPOINT
            #  value: 'tempo-tempostack-distributor.openshift-tempo-operator.svc.cluster.local:4317'
          name: qmgr
  queueManager:
    route:
      enabled: true
    name: NATIVEHAQM
    availability:
      type: NativeHA
      tls:
        secretName: mq-nativeha-internal-tls-secret
    storage:
      queueManager:
        class: PATCHED_BY_KUSTOMIZE
        deleteClaim: true
      persistedData:
        enabled: false
        class: PATCHED_BY_KUSTOMIZE
        deleteClaim: true
      recoveryLogs:
        enabled: false
        class: PATCHED_BY_KUSTOMIZE
        deleteClaim: true
    resources:
      limits:
        memory: 2Gi
      requests:
        memory: 1Gi
    mqsc:
      - configMap:
          name: native-ha-qm-configmap
          items:
            - tls.mqsc
    ini:
      - configMap:
          name: native-ha-qm-configmap
          items:
            - mq.ini
  version: 9.4.3.0-r2
  pki:
    keys:
      - name: default
        secret:
          secretName: mq-external-tls-secret
          items:
            - tls.key
            - tls.crt
    trust:
      - name: trust
        secret:
          secretName: mq-external-tls-secret
          items:
            - tls.crt
            - ca.crt
  web:
    enabled: true
    #manualConfig:
    #  secret:
    #    name: mqwebuser-secret 
