apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: native-ha-qm
  annotations:
    configmap.reloader.stakater.com/reload: "native-ha-qm-configmap"
spec:
  license:
    accept: true
    license: PATCHED_BY_KUSTOMIZE
    metric: VirtualProcessorCore
    use: PATCHED_BY_KUSTOMIZE
  securityContext:
    supplementalGroups: [99]
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: "yes"
          name: qmgr
  queueManager:
    route:
      enabled: true
    name: NATIVEHAQM
    availability:
      type: NativeHA
      tls:
        secretName: mq-nativeha-internal-tls-secret
    storage:
      queueManager:
        class: PATCHED_BY_KUSTOMIZE
        deleteClaim: true
      persistedData:
        enabled: false
        class: PATCHED_BY_KUSTOMIZE
        deleteClaim: true
      recoveryLogs:
        enabled: false
        class: PATCHED_BY_KUSTOMIZE
        deleteClaim: true
    resources:
      limits:
        memory: 2Gi
      requests:
        memory: 1Gi
    mqsc:
      - configMap:
          name: native-ha-qm-configmap
          items:
            - tls.mqsc
    ini:
      - configMap:
          name: native-ha-qm-configmap
          items:
            - mq.ini
  version: 9.3.3.0-r1
  pki:
    keys:
      - name: default
        secret:
          secretName: mq-external-tls-secret
          items:
            - tls.key
            - tls.crt
    trust:
      - name: trust
        secret:
          secretName: mq-external-tls-secret
          items:
            - tls.crt
            - ca.crt
  web:
    enabled: true
