apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mq-server-certificate
spec:
  secretName: mq-server-certificate-secret
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  commonName: lhscp4i.ceibm.com
  subject:
    organizations:
      - mq
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - key encipherment
    - digital signature
    - server auth
    - client auth
  dnsNames:
    - 'wellknown-cert-qm.mycluster-fra02-c3c-16x32-bcaeaf77ec409da3581f519c2c3bf303-0000.eu-de.containers.appdomain.cloud'
    - 'lhscp4i.ceibm.com'
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer