apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mq-server-certificate
spec:
  secretTemplate:
    annotations:
      cert-utils-operator.redhat-cop.io/generate-cert-info: "true"
  secretName: mq-server-certificate-secret
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  commonName: aro.ceibm.com
  subject:
    organizations:
      - mq
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - key encipherment
    - digital signature
    - server auth
    - client auth
  dnsNames:
    - 'wellknown-cert-qm-ibm-mq-qm-cp4i.apps.jn8qaoym.eastus.aroapp.io'
    - 'aro.ceibm.com'
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
