apiVersion: events.ibm.com/v1beta1
kind: EventEndpointManagement
metadata:
  name: eventendpointmgr
spec:
  license:
    accept: true
    license: L-CYBH-K48BZQ
    metric: VIRTUAL_PROCESSOR_CORE
    use: EventAutomationNonProduction
  manager:
    tls: 
      ui:
        secretName: default-cert-copy
      trustedCertificates:
        - secretName: letsencrypt-chain
          certificate: ca.crt
        #- secretName: apim-cpd
        #  certificate: ca.crt
    #apic:
    #  jwks:
    #    endpoint: https://apic-clust-c5f21b07-platform-api-cp4i.apps.itz-5rbxsk.infra01-lb.fra02.techzone.ibm.com/api/cloud/oauth2/certs
    authConfig:
      authType: INTEGRATION_KEYCLOAK
    storage:
      storageClassName: PATCHED_BY_KUSTOMIZE
      type: persistent-claim
    template:
      pod:
        spec:
          containers:
            - name: manager
              #env:
              #  - name: FULL_LOG_TRACE
              #    value: 'true'
              #  - name: EI_AUTH_OAUTH2_ADDITIONAL_SCOPES
              #    value: 'email,profile,offline_access'
              resources:
                limits:
                  cpu: '0.5'
                  memory: 512Mi
                requests:
                  cpu: '0.25'
                  memory: 256Mi
