apiVersion: events.ibm.com/v1beta1
kind: EventEndpointManagement
metadata:
  name: eventendpointmgr
spec:
  license:
    accept: true
    license: L-YBXJ-ADJNSM
    metric: VIRTUAL_PROCESSOR_CORE
    use: CloudPakForIntegrationNonProduction
  manager:
    authConfig:
      authType: LOCAL
    storage:
      type: ephemeral
    template:
      pod:
        spec:
          containers:
            - name: manager
              resources:
                limits:
                  cpu: '0.5'
                  memory: 512Mi
                requests:
                  cpu: '0.25'
                  memory: 256Mi
