kind: Secret
apiVersion: v1
metadata:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
  name: eventendpointmgr-ibm-eem-user-roles
stringData:
  user-mapping.json: >-
    {
    "mappings": [
        {
            "id": "admin",
            "roles": [
                "admin",
                "author"
            ]
        },
        {
            "id": "viewer",
            "roles": [
                "viewer"
            ]
        },
        {
            "id": "eventendpointmanagement-admin",
            "roles": [
                "admin",
                "author"
            ]
        },
        {
            "id": "eventendpointmanagement-viewer",
            "roles": [
                "viewer"
            ]
        },
        {
            "id": "eem-admin",
            "roles": [
                "admin"
            ]
        },
        {
            "id": "eem-author",
            "roles": [
                "author"
            ]
        },
        {
            "id": "eem-viewer",
            "roles": [
                "viewer"
            ]
        },
        {
            "id": "author",
            "roles": [
                "author"
            ]
        }
    ]
    }
type: Opaque