apiVersion: integration.ibm.com/v1beta1
kind: AssetRepository
metadata:
  name: assetrepository
spec:
  storage:
    assetDataVolume:
      class: ocs-external-storagecluster-ceph-rbd
    couchVolume:
      class: ocs-external-storagecluster-ceph-rbd