apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-apiconnect
spec:
  channel: "6.0"
  name: ibm-apiconnect
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
  config:
    resources:
      limits:
        cpu: '1'
        memory: 2Gi
      requests:
        cpu: 75m
        memory: 128Mi
