apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mq-nativeha-internal-tls
spec:
  secretName: queue-manager-ha-secret-internal
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  subject:
    organizations:
      - mq
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - key encipherment
    - digital signature
    - server auth
    - client auth
  issuerRef:
    name: mq-selfsigned-issuer