apiVersion: apiconnect.ibm.com/v1beta1
kind: APIConnectCluster
metadata:
  name: apic-cluster
  labels:
    app.kubernetes.io/instance: apiconnect
    app.kubernetes.io/managed-by: ibm-apiconnect
    app.kubernetes.io/name: apiconnect-small
spec:
  license:
    accept: true
    license: L-DZZQ-MGVN8V
    metric: VIRTUAL_PROCESSOR_CORE
    use: PATCHED_BY_KUSTOMIZE
  management:
    testAndMonitor:
      enabled: true
      autoTestEnabled: true
  analytics:
    storage:
      enabled: true
      type: shared
    #external:
    #  offload: 
    #    enabled: true
    #    output: |
    #    http {
    #      url => "https://<ENGINE_URL>/engine?structure=ibm-apiconnect"
    #      http_method => "post"
    #      codec => "json"
    #      content_type => "application/json"
    #      headers => ["x-nn-source-index", "<INDEX>", "x-nn-source-key", "<KEY>"]
    #      id => "noname-offload"
    #    }    
  profile: n1xc7.m48
  version: 10.0.8.0
  storageClassName: PATCHED_BY_KUSTOMIZE
  gateway:
  #  jaegerTracing:
  #    samplingType: const
  #    propagationFormat: w3c
  #    samplingRate: '1'
  #    agentImage: 'icr.io/instana/instana-dp-agent-image:latest'
  #    tls:
  #      disabled: true
  #      skipHostVerify: false
  #    env:
  #      - name: INSTANA_AGENT_HOST
  #        valueFrom:
  #          fieldRef:
  #            apiVersion: v1
  #            fieldPath: status.hostIP
    podAutoScaling:
      hpa:
        maxReplicas: 3
        minReplicas: 1
        targetCPUUtilizationPercentage: 90
        targetMemoryUtilizationPercentage: 80
      method: HPA
