apiVersion: apiconnect.ibm.com/v1beta1
kind: APIConnectCluster
metadata:
  name: apic-cluster
  labels:
    app.kubernetes.io/instance: apiconnect
    app.kubernetes.io/managed-by: ibm-apiconnect
    app.kubernetes.io/name: apiconnect-small
spec:
  license:
    accept: true
    license: L-KZXM-S7SNCU
    metric: VIRTUAL_PROCESSOR_CORE
    use: PATCHED_BY_KUSTOMIZE
  analytics:
    storage:
      enabled: true
      type: shared
  profile: n1xc7.m48
  version: 10.0.6.0
  storageClassName: PATCHED_BY_KUSTOMIZE
  gateway:
    podAutoScaling:
      hpa:
        maxReplicas: 3
        minReplicas: 1
        targetCPUUtilizationPercentage: 90
        targetMemoryUtilizationPercentage: 80
      method: HPA
