apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- rook-crds.yaml
- rook-operator.yaml
- rook-argo-role.yaml
- privileged-scc-rb.yaml
- nfs-roles.yaml
- pvc.yaml
- nfs-server.yaml
- platform-navigator-storageclass.yaml
- zen-configmap.yaml

patchesStrategicMerge:
- pn-noreconcile.yaml
- license-service-storage-class.yaml
