apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: native-ha-qm
spec:
  queueManager:
    storage:
      queueManager:
        class: ocs-storagecluster-ceph-rbd
      persistedData:
        class: ocs-storagecluster-ceph-rbd
      recoveryLogs:
        class: ocs-storagecluster-ceph-rbd