###############################################################################
#
# © Copyright IBM Corp. 2020, 2023, 2024
#
###############################################################################
apiVersion: eventstreams.ibm.com/v1beta2
kind: EventStreams
metadata:
  labels:
    backup.eventstreams.ibm.com/component: eventstreams
  name: minimal-prod
spec:
  version: latest
  license:
    # By installing this product you accept the license terms at https://ibm.biz/ea-license
    accept: true
    license: "L-CYBH-K48BZQ"
    use: "EventAutomationProduction"
  adminApi: {}
  adminUI:
    authentication:
      - type: integrationKeycloak
  apicurioRegistry: {}
  collector: {}
  restProducer: {}
  strimziOverrides:
    kafka:
      authorization:
        type: simple
      config:
        log.cleaner.threads: 6
        num.io.threads: 24
        num.network.threads: 9
        num.replica.fetchers: 3
        offsets.topic.replication.factor: 3
        default.replication.factor: 3
        min.insync.replicas: 2
        auto.create.topics.enable: 'false'
      listeners:
        - name: external
          port: 9094
          type: route
          tls: true
          authentication:
            type: scram-sha-512
        - name: tls
          port: 9093
          type: internal
          tls: true
          authentication:
            type: scram-sha-512
      metricsConfig:
        type: jmxPrometheusExporter
        valueFrom:
          configMapKeyRef:
            key: kafka-metrics-config.yaml
            name: minimal-prod-metrics-config
      resources:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 2048Mi
          cpu: 1000m
      storage:
        type: persistent-claim
        size: 4Gi
        class: PATCHED_BY_KUSTOMIZE
        deleteClaim: true # ensure claim is owned by CR
    nodePools:
      - name: kafka
        replicas: 3
        storage:
          type: persistent-claim
          size: 2Gi
          class: PATCHED_BY_KUSTOMIZE
        roles:
          - broker
      - name: controller
        replicas: 3
        storage:
          type: persistent-claim
          size: 2Gi
          class: PATCHED_BY_KUSTOMIZE
        roles:
          - controller