apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cp4i-operands
spec:
  generators:
  - list:
      elements:
        #- name: apiconnect
        #  namespace: cp4i
        #  sync-wave: "300"
        #  target-revision: HEAD
        - name: mq
          namespace: cp4i
          sync-wave: "300"
          target-revision: HEAD
        - name: appconnect
          namespace: cp4i
          sync-wave: "300"
          target-revision: HEAD
        - name: eventstreams
          namespace: cp4i
          sync-wave: "300"
          target-revision: HEAD
        - name: platformnavigator
          namespace: cp4i
          sync-wave: "200"
          target-revision: HEAD
        - name: openshift-logging
          namespace: openshift-logging
          sync-wave: "200"
          target-revision: HEAD
        - name: openshift-monitoring
          namespace: openshift-monitoring
          sync-wave: "200"
          target-revision: HEAD
  template:
    metadata:
      name: '{{name}}'
      labels:
        group: applications
      annotations:
        argocd.argoproj.io/sync-wave: '{{sync-wave}}'
    spec:
      project: 'cp4i-operands'
      source:
        repoURL: https://github.com/Nordic-MVP-GitOps-Repos/hypersonic-lightweight-cp4i.git
        targetRevision: '{{target-revision}}'
        path: 'envs/ibm-classic/nonprod/{{name}}/'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          selfHeal: true
      ignoreDifferences:
      - group: appconnect.ibm.com
        kind: Configuration
        jsonPointers:
          - /spec/data
