apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cp4i-operands
spec:
  generators:
  - list:
      elements:
        #- name: apiconnect
        #  namespace: cp4i
        #  sync-wave: "300"
        # - name: mq
        #   namespace: cp4i
        #   sync-wave: "300"
        # - name: appconnect
        #   namespace: cp4i
        #   sync-wave: "300"
        - name: eventstreams
          namespace: cp4i
          sync-wave: "300"
        - name: platformnavigator
          namespace: cp4i
          sync-wave: "200"
        - name: openshift-logging
          namespace: openshift-logging
          sync-wave: "200"
        - name: openshift-monitoring
          namespace: openshift-monitoring
          sync-wave: "200"
        - name: reloader
          namespace: cp4i
          sync-wave: "200"
          target-revision: HEAD
        #- name: instana-agent
        #  namespace: instana-agent
        #  sync-wave: "200"
        #  target-revision: HEAD
        #- name: clusterresourceoverride
        #  namespace: cp4i
        #  sync-wave: "200"
        #  target-revision: HEAD
        # - name: assetrepository
        #  namespace: cp4i
        #  sync-wave: "200"
        #  target-revision: HEAD
  template:
    metadata:
      name: '{{name}}'
      labels:
        group: applications
      annotations:
        argocd.argoproj.io/sync-wave: '{{sync-wave}}'
    spec:
      project: 'cp4i-operands'
      source:
<<<<<<< HEAD
        path: 'envs/odf/nonprod/{{name}}/'
=======
        path: 'envs/ibm-classic/nonprod/{{name}}/'
>>>>>>> 178c689 (Adding ODF storage env)
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          selfHeal: true
      ignoreDifferences:
      - group: appconnect.ibm.com
        kind: Configuration
        jsonPointers:
          - /spec/data
