apiVersion: apiconnect.ibm.com/v1beta1
kind: Product
metadata:
  name: animals-facts-product
spec:
  state: Published
  definition:
    product: 1.0.0
    info:
      title: 1. Animal Facts REST APIs
      name: animal-facts-product
      description: >-
        A collection of animal fact REST APIs - contains facts and breeds for cats and dogs
      version: '1.0'
      categories:
        - Domain/Payments
        - Protocol/REST
    plans:
      default-plan:
        rate-limits:
          default:
            value: 700/1hour
        title: Default Plan
        description: Default Plan
        approval: false
  apis:
    apis:
      - name: cat-facts-api
      - name: dog-facts-api
  share:
    apim:
      providerOrg: test
      catalog: sandbox
      credentialsSecret: apim-credentials
---
apiVersion: apiconnect.ibm.com/v1beta1
kind: API
metadata:
  name: cat-facts-api
spec:
  definition:
    configMap: cat-facts-api-cm
---
apiVersion: apiconnect.ibm.com/v1beta1
kind: API
metadata:
  name: dog-facts-api
spec:
  definition:
    configMap: dog-facts-api-cm