apiVersion: apiconnect.ibm.com/v1beta1
kind: Product
metadata:
  name: countries-product
spec:
  state: Published
  definition:
    product: 1.0.0
    info:
      title: 2. Countries GraphQL API
      name: countries-product
      description: >-
        This is a public GraphQL API for information about countries, continents, and languages.
      version: '1.0'
      categories:
        - Domain/Accounts
        - Protocol/GraphQL
    plans:
      default-plan:
        rate-limits:
          default:
            value: 1000/1hour
        title: Default Plan
        description: Default Plan
        approval: false
  apis:
    apis:
      - name: countries-gql-api
  share:
    apim:
      providerOrg: providerorg
      catalog: sandbox
      credentialsSecret: apim-credentials
---
apiVersion: apiconnect.ibm.com/v1beta1
kind: API
metadata:
  name: countries-gql-api
spec:
  definition:
    configMap: countries-gql-api-cm