apiVersion: apiconnect.ibm.com/v1beta1
kind: Product
metadata:
  name: datetime-product
spec:
  state: Published
  definition:
    product: 1.0.0
    info:
      title: 7. Datetime APIs
      name: datetime-product
      description: >-
        Illustration of an API that uses an existing App Connect integrationruntime
      version: '1.0'
      categories:
        - Domain/Dates
        - Protocol/REST
    plans:
      default-plan:
        rate-limits:
          default:
            value: 700/1hour
        title: Default Plan
        description: Default Plan
        approval: false
  share:
    apim:
      providerOrg: providerorg
      catalog: sandbox
      credentialsSecret: apim-credentials
  apis:
    integrationRuntimes:
      - name: sample-integrationruntime
        security:
          type: NoOp