apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  - animals-product.yaml
  - countries-product.yaml
  - vehicle-info-product.yaml
  #- building-events-product.yaml
  - mq-product.yaml
  - rabbitmq-product.yaml
  - datetime-product.yaml

patches:
  - target:
      version: v1beta1
      group: apiconnect.ibm.com
      kind: Product
    path: add-apim-credentials.yaml