apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-appconnect
spec:
  channel: v11.3
  name: ibm-appconnect
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
  config:
    resources:
      limits:
        ephemeral-storage: 512Mi
        memory: 1.5Gi
      requests:
        cpu: 100m
        ephemeral-storage: 50Mi
        memory: 128Mi
