apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apic-apis
  namespace: openshift-gitops
spec:
  destination:
    namespace: cp4i
    server: https://kubernetes.default.svc
  project: cp4i-operands
  source:
    path: ./components/apiconnect/base/apis/
    targetRevision: update-16.1.0
    repoURL: https://github.com/Nordic-MVP-GitOps-Repos/hypersonic-lightweight-cp4i.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
