kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cp4i-argo-rb
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    #name: openshift-gitops-otp-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cp4i-argo-role