apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: post-sync-job-license-service-reporter-role
  namespace: ibm-common-services
rules:
  - apiGroups:
      - operator.ibm.com
    resources:
      - operandconfigs
    verbs:
      - '*'
