apiVersion: eventstreams.ibm.com/v1beta2
kind: EventStreams
metadata:
  name: minimal-prod
spec:
  strimziOverrides:
    kafka:
      storage:
        class: ocs-external-storagecluster-ceph-rbd
    nodePools:
      - name: kafka
        replicas: 3
        storage:
          class: ocs-external-storagecluster-ceph-rbd
          type: persistent-claim
          size: 2Gi
        roles:
          - broker
      - name: controller
        replicas: 3
        storage:
          class: ocs-external-storagecluster-ceph-rbd
          type: persistent-claim
          size: 2Gi
        roles:
          - controller

   