apiVersion: eventstreams.ibm.com/v1beta2
kind: EventStreams
metadata:
  name: minimal-prod
spec:
  strimziOverrides:
    kafka:
      storage:
        class: ocs-external-storagecluster-ceph-rbd
    zookeeper:
      storage:
        class: ocs-external-storagecluster-ceph-rbd