  kind: Deployment
  apiVersion: apps/v1
  metadata:
    name: mq-metrics-otel
    namespace: cp4i
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: mq-metric-exporter-otel
    template:
      metadata:
        labels:
          app: mq-metric-exporter-otel
      spec:
        containers:
          - name: mq-metric-exporter-otel
            image: 'image-registry.openshift-image-registry.svc:5000/cp4i/mq-metrics-otel:latest'
            envFrom:
            - secretRef:
                name: empty-metrics-credentials
            ports:
            - containerPort: 9157
              name: web
            volumeMounts:
              - name: config-vol
                mountPath: /opt/config
        volumes:
        - name: config-vol
          configMap:
            name: otel-config-file
            items:
              - key: file
                path: mq_otel.yaml
