kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: copy-default-ingress-cert-rb
subjects:
  - kind: ServiceAccount
    name: copy-default-ingress-cert-sa
    namespace: cp4i
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: copy-default-ingress-cert-role
