apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 
  - messagingserver.yaml
  - channel.yaml
  - user.yaml
  - queue-a.yaml
  - queue-b.yaml

patches:
  - target:
      version: v1beta1
      group: integration.ibm.com
      kind: MessagingServer
    path: add-license-and-version.yaml
  