apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  - common-service.yaml 
  - platform-navigator.yaml

  #- license-server-reporter
  # - iam-customhostname.yaml
  # - cs-onprem-tenant-config.yaml
  # Platform navigator brings in common services which brings in cert manager, so ClusterIssuer will be available.
  #- letsencrypt-clusterissuer.yaml
