apiVersion: integration.ibm.com/v1beta1
kind: PlatformNavigator
metadata:
  name: platform-navigator
  labels:
    backup.integration.ibm.com/component: platformnavigator        
spec:
  license:
    accept: true
    license: L-VTPK-22YZPK
  replicas: 1
  version: 2023.4.1