apiVersion: integration.ibm.com/v1beta1
kind: PlatformNavigator
metadata:
  name: platform-navigator
  labels:
    backup.integration.ibm.com/component: platformnavigator        
spec:
  license:
    accept: true
    license: L-JTPV-KYG8TF
  replicas: 1
  version: 16.1.0