apiVersion: integration.ibm.com/v1beta1
kind: PlatformNavigator
metadata:
  name: platform-navigator
spec:
  license:
    accept: true
    license: L-VTPK-22YZPK
  mqDashboard: true
  replicas: 1
  storage:
    class: PATCHED_BY_KUSTOMIZE
  version: 2023.4.1
  #requestIbmServices:
  #  licensing: true
  # See: https://www.ibm.com/docs/en/cloud-paks/cp-integration/2022.4?topic=certificates-using-custom-hostnames-platform-ui
  #tls:
  #  secretName: "your-custom-certs-secret"
  #  serverCertificate: tls.crt
  #  caCertificate: ca.crt
  #  key: tls.key
  #uiHostname: "cpd.lhscp4i.ceibm.com"
