apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-integration-platform-navigator
spec:
  channel: "v7.3-sc2"
  name: ibm-integration-platform-navigator
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
  config:
    resources:
      limits:
        cpu: 200m
        memory: 1.5Gi
      requests:
        cpu: 200m
        memory: 1Gi
