apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: wellknown-cert-qm
  annotations:
    certmanager.k8s.io/disable-auto-restart: "true"
    configmap.reloader.stakater.com/reload: "wellknown-cert-qm-configmap"
    secret.reloader.stakater.com/reload: "mq-server-certificate-secret,mq-nativeha-internal-tls-secret,letsencrypt-chain"
spec:
  license:
    accept: true
    license: PATCHED_BY_KUSTOMIZE
    metric: VirtualProcessorCore
    use: PATCHED_BY_KUSTOMIZE
  securityContext:
    supplementalGroups: [99]
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: "yes"
          name: qmgr
  queueManager:
    route:
      enabled: true
    name: CERTQM
    availability:
      type: NativeHA
      tls:
        secretName: mq-nativeha-internal-tls-secret
    storage:
      queueManager:
        class: PATCHED_BY_KUSTOMIZE
        deleteClaim: true
      persistedData:
        enabled: false
        class: PATCHED_BY_KUSTOMIZE
        deleteClaim: true
      recoveryLogs:
        enabled: false
        class: PATCHED_BY_KUSTOMIZE
        deleteClaim: true
    resources:
      limits:
        memory: 2Gi
      requests:
        memory: 2Gi
    mqsc:
      - configMap:
          name: wellknown-cert-qm-configmap
          items:
            - tls.mqsc
    ini:
      - configMap:
          name: wellknown-cert-qm-configmap
          items:
            - mq.ini
  version: 9.4.1.0-r2
  pki:
    keys:
      - name: default
        secret:
          # Use this or create your own certificate by modifying tls/mq-server-certificate.yaml dnsNames.
          secretName: default-cert-copy
          items:
            - tls.key
            - tls.crt
    trust:
      - name: letsencrypt
        secret:
          secretName: letsencrypt-chain
          items:
            - ca.crt
  web:
    enabled: true
